### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by yemlahi** [jhuckaby/Effect-Games#2]
Hello everybody,

Is there any "Admin" account we can use in order to use Effect Games.

**Comment by jhuckaby** [comment]
Yes, an administrator user is created automatically as part of the "setup_db.pl" script, which you must run.  The username is "admin" and the password is "admin".  This is documented at the bottom of the Installation Guide:

https://github.com/jhuckaby/Effect-Games/wiki/Installation-Guide

Good luck!

**Comment by yemlahi** [comment]
Ok, thank you.

**Comment by jhuckaby** [comment]
Hey yemlahi, you are trying to login to the REAL live public "EffectGames.com" as the administrator user.  I just received an e-mail saying someone is trying to change the admin password.  You need to login to your OWN server, not the www.effectgames.com live site.
