### ISSUE TITLE
Sourcecode for Canvas Cycle

### ISSUE THREAD

**Issue by lrq3000** [jhuckaby/Effect-Games#8]
Hello there!

Your work is amazing! Not really an issue, but on your github, the sourcecode for the [Canvas Cycle demo](http://www.effectgames.com/demos/canvascycle/) is missing, and the original link does not work anymore. I would really like to download it, as I find this demo so very beautiful!

Would it be possible to reupload the sourcecode on github? Thank you very much in advance!

Best regards,
Lrq3000

**Comment by jhuckaby** [comment]
Hi there!

Sorry about the broken link.  The link to the original blog article can be found here:

http://www.effectgames.com/effect/article-Old_School_Color_Cycling_with_HTML5.html

You can download the source code by clicking the button at the bottom of that page, or here:

http://www.effectgames.com/demos/canvascycle/canvascycle-source.zip

Thanks!

**Comment by lrq3000** [comment]
Perfect, thanks a lot! :-D

But if I can suggest, I really think you should publish it on github, this will give it more visibility :-)

**Comment by jhuckaby** [comment]
You bet.

Yup, I'll do that.  This little demo is very old (circa 2010) and predates my GitHub account, so it just never happened.  I should check it in one of these days tho :)

**Comment by thg2k** [comment]
I ran into the same issue, I suspect you never managed to publish that canvascycle demo on GitHub right?

Would you mind if I publish it? Of course if you can manage it would be more official

**Comment by jhuckaby** [comment]
Sure thing, here you go: https://github.com/jhuckaby/canvascycle
